### PR TITLE
Fixes deprecation warning: PHP Deprecated:  Comments starting with '#…

### PR DESCRIPTION
**Pull request by pietervogelaar**
Fixes deprecation warning: PHP Deprecated:  Comments starting with '#' are deprecated in Unknown on line 1 in Unknown on line 0

### CODE REVIEW

**Comment by stajkowski** [comment]
Can one of the admins verify this patch?

**Comment by stajkowski** [comment]
Can one of the admins verify this patch?

**Comment by stajkowski** [comment]
Can one of the admins verify this patch?

**Comment by stajkowski** [comment]
Can one of the admins verify this patch?

**Comment by stajkowski** [comment]
Can one of the admins verify this patch?

**Comment by stajkowski** [comment]
Can one of the admins verify this patch?

**Comment by stajkowski** [comment]
Can one of the admins verify this patch?

**Comment by saintberry** [comment]
@pietervogelaar You should also update the comments that get written from the provider: https://github.com/pietervogelaar/php5-fpm/blob/master/providers/pool.rb#L235

Thanks for the patch. Hopefully it can be merged.

**Pull request merged**
